import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import auth2faRouter from "./auth-2fa";
import dashboardRouter from "./dashboard";
import curriculumRouter from "./curriculum";
import questionsRouter from "./questions";
import testsRouter from "./tests";
import flashcardsRouter from "./flashcards";
import userQuestionStateRouter from "./userQuestionState";
import learningHubRouter from "./learning-hub";
import analyticsRouter from "./analytics";
import aiBookstoreRouter from "./ai-bookstore";
import aiExplainRouter from "./ai-explain";
import aiVerificationRouter from "./ai-verification";
import aiGenerationRouter from "./ai-generation";
import aiGradingRouter from "./ai-grading";
import aiChatRouter from "./ai-chat";
import textbooksRouter from "./textbooks";
import filesRouter from "./files";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(auth2faRouter);
router.use(dashboardRouter);
router.use(curriculumRouter);
router.use(questionsRouter);
router.use(testsRouter);
router.use(flashcardsRouter);
router.use(userQuestionStateRouter);
router.use(learningHubRouter);
router.use(analyticsRouter);
router.use(aiBookstoreRouter);
router.use(aiExplainRouter);
router.use(aiVerificationRouter);
router.use(aiGenerationRouter);
router.use(aiGradingRouter);
router.use(aiChatRouter);
router.use(textbooksRouter);
router.use(filesRouter);

export default router;
